sonar.projectKey=sebasmg25_back-cotionline
sonar.organization=sebasmg25
sonar.host.url=https://sonarcloud.io
sonar.token=abfcaf969a4f6e09f8f4119637fd0bd068dd4451
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.test.inclusions=tests/**/*.spec.ts
sonar.typescript.tsconfigPath=tsconfig.json


sonar.coverage.exclusions=src/apps/**, src/**/infraestructure/**, src/**/interfaces/**, src/**/domain/**, src/contexts/shared/**
